apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend
    tier: frontend
spec:
  selector:
    matchLabels:
      app: httpd-frontend
  replicas: 3
  template: 
    metadata: 
      name: httpd:2.4-alpine
      labels:
        app: httpd-frontend
    spec:
      containers:
        - name: httpd:2.4-alpine
          image: httpd:2.4-alpine